DROP DATABASE IF EXISTS practica42;
CREATE DATABASE practica42;
USE practica42;

CREATE TABLE tiendas (
	NIF VARCHAR(10),
	NOMBRE VARCHAR(20),
	DIRECCION VARCHAR(20),
	POBLACION VARCHAR(20),
	PROVINCIA VARCHAR(20),
	CODPOSTAL INT(5)
);

ALTER TABLE tiendas ADD CONSTRAINT PRIMARY KEY (NIF);
ALTER TABLE tiendas ADD CONSTRAINT CHECK (PROVINCIA = UPPER(PROVINCIA));
ALTER TABLE tiendas MODIFY NOMBRE VARCHAR(30) NOT NULL;

CREATE TABLE fabricantes (
	COD_FABRICANTE INT(3) PRIMARY KEY,
	NOMBRE VARCHAR(15) CHECK (NOMBRE = UPPER(NOMBRE)),
	PAIS VARCHAR(15) CHECK (PAIS = UPPER(PAIS))
);

CREATE TABLE articulos (
	ARTICULO VARCHAR(20),
	COD_FABRICANTE INT(3),
	PESO INT(3) CHECK (PESO > 0),
	CATEGORIA VARCHAR(10) CHECK (CATEGORIA IN ('Primera','Segunda','Tercera')),
	PRECIO_VENTA FLOAT(6) CHECK (PRECIO_VENTA > 0),
	PRECIO_COSTO FLOAT(6) CHECK (PRECIO_COSTO > 0),
	EXISTENCIAS INT(5),
	CONSTRAINT PK_ARTICULOS PRIMARY KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA),
	CONSTRAINT FK_ARTICULOS FOREIGN KEY (COD_FABRICANTE) REFERENCES fabricantes(COD_FABRICANTE)
);

CREATE TABLE ventas (
	NIF VARCHAR(10),
	ARTICULO VARCHAR(20),
	COD_FABRICANTE INT(3),
	PESO INT(3),
	CATEGORIA VARCHAR(10) CHECK (CATEGORIA IN ('Primera','Segunda','Tercera')),
	FECHA_VENTA DATE,
	UNIDADES_VENDIDAS INT(4) CHECK (UNIDADES_VENDIDAS > 0),
	CONSTRAINT PK_VENTAS PRIMARY KEY (NIF, ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, FECHA_VENTA),
	CONSTRAINT FK_VENTAS_NIF FOREIGN KEY (NIF) REFERENCES tiendas(NIF),
	CONSTRAINT FK_VENTAS_VARIOS FOREIGN KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES articulos(ARTICULO, COD_FABRICANTE, PESO, CATEGORIA)
);

CREATE TABLE pedidos(
	NIF VARCHAR(10),
	ARTICULO VARCHAR(20),
	COD_FABRICANTE INT(3),
	PESO INT(3),
	CATEGORIA VARCHAR(10) CHECK (CATEGORIA IN ('Primera','Segunda','Tercera')),
);
